# fly.toml app configuration file generated for omnidemo-frontend on 2025-04-01T17:04:23-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omnidemo-frontend'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'
  [build.args]
    API_URL = "https://omnidemo-backend.fly.dev/" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
