-- create table public.forecasts (
--   id bigint generated by default as identity not null,
--   file_id character varying null,
--   created_at timestamp with time zone not null default now(),
--   job_id character varying null,
--   status character varying not null,
--   constraint forecasts_pkey primary key (id)
-- ) TABLESPACE pg_default;

CREATE TABLE forecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    file_id TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    job_id TEXT NULL,
    status TEXT NOT NULL
);

-- create table public.charts (
--   id bigint generated by default as identity not null,
--   forecast_id bigint not null,
--   created_at timestamp with time zone not null default now(),
--   chart_key character varying not null,
--   data jsonb null,
--   constraint charts_pkey primary key (id),
--   constraint charts_forecast_id_fkey foreign KEY (forecast_id) references forecasts (id)
-- ) TABLESPACE pg_default;

CREATE TABLE charts (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    forecast_id INTEGER NOT NULL,
    chart_key TEXT NOT NULL,
    data TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (forecast_id) REFERENCES forecasts (id)
);

-- create table public.inputs (
--   id uuid not null default gen_random_uuid (),
--   file_name character varying not null,
--   stored_name character varying not null,
--   username character varying not null,
--   size bigint not null,
--   created_at timestamp with time zone not null default now(),
--   constraint inputs_pkey primary key (id)
-- ) TABLESPACE pg_default;

CREATE TABLE inputs (
    id TEXT PRIMARY KEY NOT NULL,
    file_name TEXT NOT NULL,
    stored_name TEXT NOT NULL,
    username TEXT NOT NULL,
    size INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- create table public.insights (
--   id bigint generated by default as identity not null,
--   message text null,
--   username text null,
--   created_at timestamp with time zone not null default now(),
--   constraint insights_pkey primary key (id)
-- ) TABLESPACE pg_default;

CREATE TABLE insights (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    message TEXT NULL,
    username TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- create table public.jobs (
--   id uuid not null default gen_random_uuid (),
--   progress real not null default '0'::real,
--   status character varying not null,
--   error text null,
--   created_at timestamp with time zone not null default now(),
--   constraint jobs_pkey primary key (id)
-- ) TABLESPACE pg_default;

CREATE TABLE jobs (
    id TEXT PRIMARY KEY NOT NULL,
    progress REAL NOT NULL DEFAULT 0,
    status TEXT NOT NULL,
    error TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- create table public.user_charts (
--   id bigint generated by default as identity not null,
--   username character varying not null,
--   chart_key character varying not null,
--   created_at timestamp with time zone not null default now(),
--   constraint user_charts_pkey primary key (id)
-- ) TABLESPACE pg_default;

CREATE TABLE user_charts (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT NOT NULL,
    chart_key TEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
